name: Gopen 

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  check-release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Verify release notes changes
        uses: tj-actions/verify-changed-files@v5.5
        id: changed_files
        with:
          files: |
             .github/workflows/ci-pipeline.yaml
      - name: Check release notees changes
        if: steps.changed_files.outputs.files_changed == 'false'
        run: echo "YOU must add and change the release notes"

  build:
    runs-on: ubuntu-latest
    needs: check-release-notes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build binaries
        run: |
          make artifact
      - name: Release with Notes
        uses: softprops/action-gh-release@v1
        with:
          files: build/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

