on:
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3.6.1
        with:
          go-version: "1.24"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5.0.0
      - name: Build
        run: |
          go build -v .

  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3.6.1
        with:
          go-version: "1.24"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5.0.0
      - name: Unit testing
        run: |
          go test -v -cover .
