on:
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: "1.18"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.0.2
      - name: Build
        run: |
          go build -v .

  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3.2.0
        with:
          go-version: "1.18"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.0.2
      - name: Unit testing
        run: |
          go test -v -cover .
