on:
  pull_request:
    paths-ignore:
      - "README.md"
  push:
    paths-ignore:
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.18"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4
      - name: Build
        run: |
          go build -v .

  test:
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: "1.18"
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.4
      - name: TF acceptance tests
        run: |
          go test -v -cover .
